### PR TITLE
Update and rename strings.xml to strings-ru.xml

### PR DESCRIPTION
**Pull request by OmlineEditor**
I translated into Russian, but some of the variables are not clear to me. I do not know where they are used and how to translate them correctly because I haven’t seen them.

### CODE REVIEW

**Comment by OmlineEditor** [comment]
I don't know how to make translations and do Pull requests. tell me if you need something else

**Comment by Keidan** [comment]
Thanks a lot, the file is not in the right place (normally it should be called string.xml and be in the values-ru-rRU directory)

Can you add the following translation:
<string name="save_file">Save file '%1$s'?</string>

The translation does not exist yet but it will be introduced in the commit of issue #29

If the build fails with the addition of the translation, it doesn't matter I'll fix it tonight after work.

**Comment by OmlineEditor** [comment]
this is my first "Pull requests". I don’t know a lot and don’t know how to do it correctly and how to move files to the desired folder. 

for translation:
Save file '%1$s'?

Russian translation:
Сохранить файл '%1$s'?

Perhaps the translation is not correct. I don't know when this question is used. I need to look in the program where this item will be. make it possible to choose which language to use in the program, so I can switch between languages and understand where the translation needs to be corrected.

**Comment by Keidan** [comment]
Don't worry, it's already good to have additional translations :)

For the "Save file '%1$s'?", it'll be displayed in a confirmation box when you click close after a modification.

**Pull request merged**
